/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RelatoriosRouteImport } from './routes/relatorios'
import { Route as PublicacaoRouteImport } from './routes/publicacao'
import { Route as ImagensRouteImport } from './routes/imagens'
import { Route as CriarRouteImport } from './routes/criar'
import { Route as ComentariosRouteImport } from './routes/comentarios'
import { Route as ClientesRouteImport } from './routes/clientes'
import { Route as CalendarioRouteImport } from './routes/calendario'
import { Route as BibliotecaRouteImport } from './routes/biblioteca'
import { Route as AutomaticoRouteImport } from './routes/automatico'
import { Route as AprovacaoRouteImport } from './routes/aprovacao'
import { Route as AgendamentoRouteImport } from './routes/agendamento'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiGenerateImageRouteImport } from './routes/api/generate-image'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatoriosRoute = RelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicacaoRoute = PublicacaoRouteImport.update({
  id: '/publicacao',
  path: '/publicacao',
  getParentRoute: () => rootRouteImport,
} as any)
const ImagensRoute = ImagensRouteImport.update({
  id: '/imagens',
  path: '/imagens',
  getParentRoute: () => rootRouteImport,
} as any)
const CriarRoute = CriarRouteImport.update({
  id: '/criar',
  path: '/criar',
  getParentRoute: () => rootRouteImport,
} as any)
const ComentariosRoute = ComentariosRouteImport.update({
  id: '/comentarios',
  path: '/comentarios',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesRoute = ClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarioRoute = CalendarioRouteImport.update({
  id: '/calendario',
  path: '/calendario',
  getParentRoute: () => rootRouteImport,
} as any)
const BibliotecaRoute = BibliotecaRouteImport.update({
  id: '/biblioteca',
  path: '/biblioteca',
  getParentRoute: () => rootRouteImport,
} as any)
const AutomaticoRoute = AutomaticoRouteImport.update({
  id: '/automatico',
  path: '/automatico',
  getParentRoute: () => rootRouteImport,
} as any)
const AprovacaoRoute = AprovacaoRouteImport.update({
  id: '/aprovacao',
  path: '/aprovacao',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendamentoRoute = AgendamentoRouteImport.update({
  id: '/agendamento',
  path: '/agendamento',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateImageRoute = ApiGenerateImageRouteImport.update({
  id: '/api/generate-image',
  path: '/api/generate-image',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agendamento': typeof AgendamentoRoute
  '/aprovacao': typeof AprovacaoRoute
  '/automatico': typeof AutomaticoRoute
  '/biblioteca': typeof BibliotecaRoute
  '/calendario': typeof CalendarioRoute
  '/clientes': typeof ClientesRoute
  '/comentarios': typeof ComentariosRoute
  '/criar': typeof CriarRoute
  '/imagens': typeof ImagensRoute
  '/publicacao': typeof PublicacaoRoute
  '/relatorios': typeof RelatoriosRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/generate-image': typeof ApiGenerateImageRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agendamento': typeof AgendamentoRoute
  '/aprovacao': typeof AprovacaoRoute
  '/automatico': typeof AutomaticoRoute
  '/biblioteca': typeof BibliotecaRoute
  '/calendario': typeof CalendarioRoute
  '/clientes': typeof ClientesRoute
  '/comentarios': typeof ComentariosRoute
  '/criar': typeof CriarRoute
  '/imagens': typeof ImagensRoute
  '/publicacao': typeof PublicacaoRoute
  '/relatorios': typeof RelatoriosRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/generate-image': typeof ApiGenerateImageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agendamento': typeof AgendamentoRoute
  '/aprovacao': typeof AprovacaoRoute
  '/automatico': typeof AutomaticoRoute
  '/biblioteca': typeof BibliotecaRoute
  '/calendario': typeof CalendarioRoute
  '/clientes': typeof ClientesRoute
  '/comentarios': typeof ComentariosRoute
  '/criar': typeof CriarRoute
  '/imagens': typeof ImagensRoute
  '/publicacao': typeof PublicacaoRoute
  '/relatorios': typeof RelatoriosRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/generate-image': typeof ApiGenerateImageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agendamento'
    | '/aprovacao'
    | '/automatico'
    | '/biblioteca'
    | '/calendario'
    | '/clientes'
    | '/comentarios'
    | '/criar'
    | '/imagens'
    | '/publicacao'
    | '/relatorios'
    | '/sitemap.xml'
    | '/api/generate-image'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agendamento'
    | '/aprovacao'
    | '/automatico'
    | '/biblioteca'
    | '/calendario'
    | '/clientes'
    | '/comentarios'
    | '/criar'
    | '/imagens'
    | '/publicacao'
    | '/relatorios'
    | '/sitemap.xml'
    | '/api/generate-image'
  id:
    | '__root__'
    | '/'
    | '/agendamento'
    | '/aprovacao'
    | '/automatico'
    | '/biblioteca'
    | '/calendario'
    | '/clientes'
    | '/comentarios'
    | '/criar'
    | '/imagens'
    | '/publicacao'
    | '/relatorios'
    | '/sitemap.xml'
    | '/api/generate-image'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgendamentoRoute: typeof AgendamentoRoute
  AprovacaoRoute: typeof AprovacaoRoute
  AutomaticoRoute: typeof AutomaticoRoute
  BibliotecaRoute: typeof BibliotecaRoute
  CalendarioRoute: typeof CalendarioRoute
  ClientesRoute: typeof ClientesRoute
  ComentariosRoute: typeof ComentariosRoute
  CriarRoute: typeof CriarRoute
  ImagensRoute: typeof ImagensRoute
  PublicacaoRoute: typeof PublicacaoRoute
  RelatoriosRoute: typeof RelatoriosRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiGenerateImageRoute: typeof ApiGenerateImageRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorios': {
      id: '/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof RelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publicacao': {
      id: '/publicacao'
      path: '/publicacao'
      fullPath: '/publicacao'
      preLoaderRoute: typeof PublicacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/imagens': {
      id: '/imagens'
      path: '/imagens'
      fullPath: '/imagens'
      preLoaderRoute: typeof ImagensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/criar': {
      id: '/criar'
      path: '/criar'
      fullPath: '/criar'
      preLoaderRoute: typeof CriarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comentarios': {
      id: '/comentarios'
      path: '/comentarios'
      fullPath: '/comentarios'
      preLoaderRoute: typeof ComentariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes': {
      id: '/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof ClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendario': {
      id: '/calendario'
      path: '/calendario'
      fullPath: '/calendario'
      preLoaderRoute: typeof CalendarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/biblioteca': {
      id: '/biblioteca'
      path: '/biblioteca'
      fullPath: '/biblioteca'
      preLoaderRoute: typeof BibliotecaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/automatico': {
      id: '/automatico'
      path: '/automatico'
      fullPath: '/automatico'
      preLoaderRoute: typeof AutomaticoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aprovacao': {
      id: '/aprovacao'
      path: '/aprovacao'
      fullPath: '/aprovacao'
      preLoaderRoute: typeof AprovacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agendamento': {
      id: '/agendamento'
      path: '/agendamento'
      fullPath: '/agendamento'
      preLoaderRoute: typeof AgendamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-image': {
      id: '/api/generate-image'
      path: '/api/generate-image'
      fullPath: '/api/generate-image'
      preLoaderRoute: typeof ApiGenerateImageRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgendamentoRoute: AgendamentoRoute,
  AprovacaoRoute: AprovacaoRoute,
  AutomaticoRoute: AutomaticoRoute,
  BibliotecaRoute: BibliotecaRoute,
  CalendarioRoute: CalendarioRoute,
  ClientesRoute: ClientesRoute,
  ComentariosRoute: ComentariosRoute,
  CriarRoute: CriarRoute,
  ImagensRoute: ImagensRoute,
  PublicacaoRoute: PublicacaoRoute,
  RelatoriosRoute: RelatoriosRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiGenerateImageRoute: ApiGenerateImageRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
