REVOKE ALL ON FUNCTION public.handle_new_user_role() FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.handle_new_user() FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.update_updated_at_column() FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.has_role(uuid, public.app_role) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.has_role(uuid, public.app_role) TO authenticated;
REVOKE ALL ON FUNCTION public.owns_company(uuid) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.owns_company(uuid) TO authenticated;
REVOKE ALL ON FUNCTION public.owns_post(uuid) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.owns_post(uuid) TO authenticated;
REVOKE ALL ON FUNCTION public.admin_platform_stats() FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.admin_platform_stats() TO authenticated;